// Code generated by hertz generator.

package main

import (
	_  "github.com/cloudwego/biz/douyin_db"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
//	err := douyin_db.Form_tables()
}

func main() {
	h := server.New(server.WithMaxRequestBodySize(400*1024*1024))

	register(h)
	h.Spin()
}
