// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/biz/douyin_db"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
	err := douyin_db.Form_tables()
	if err != nil {
		panic("db migate error")
	}
}

func main() {
	h := server.Default()

	register(h)
	h.Spin()
}
