// Code generated by hertz generator.

package douyin_core

import (
	"context"
  "fmt"
	douyin_core "github.com/cloudwego/biz/model/douyin_core"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateFeedResponse .
// @router /douyin/feed/ [GET]
func CreateFeedResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinFeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
  fmt.Println("douyin/feed")
  var code int32=0
  var msg string="hello"
  var vlist []*douyin_core.Video
  var nexttime int64 = 100000
	resp := &douyin_core.DouyinFeedResponse{
    StatusCode: code,
    StatusMsg: msg,
    VideoList: vlist,
    NextTime: nexttime,
  }

	c.JSON(consts.StatusOK, resp)
}
