// Code generated by hertz generator.

package douyin_core

import (
	"context"

	douyin_core "github.com/cloudwego/biz/model/douyin_core"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreatePublishListResponse .
// @router /douyin/publish/list/ [GET]
func CreatePublishListResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinPublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(douyin_core.DouyinPublishListResponse)

	c.JSON(consts.StatusOK, resp)
}
