// Code generated by hertz generator.

package douyin_core

import (
	"context"

	douyin_core "github.com/cloudwego/biz/model/douyin_core"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreatePublishActionResponse .
// @router /douyin/publish/action/ [POST]
func CreatePublishActionResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_core.DouyinPublishActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(douyin_core.DouyinPublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}
