// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	douyin_core "github.com/cloudwego/biz/router/douyin_core"
	douyin_extra_first "github.com/cloudwego/biz/router/douyin_extra_first"
	douyin_extra_second "github.com/cloudwego/biz/router/douyin_extra_second"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	douyin_extra_second.Register(r)

	douyin_extra_first.Register(r)

	douyin_core.Register(r)
}
