// Code generated by hertz generator.

package douyin_extra_first

import (
	"context"

	douyin_extra_first "github.com/cloudwego/biz/model/douyin_extra_first"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateCommentActionResponse .
// @router /douyin/comment/action/ [POST]
func CreateCommentActionResponse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req douyin_extra_first.DouyinCommentActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(douyin_extra_first.DouyinCommentActionResponse)

	c.JSON(consts.StatusOK, resp)
}
